#!/bin/bash 
##sh check_last_processed_delay InteractionMessageEvent,InteractionStateEvent,AgentSessionEvent 2000000 "Pushing chronos event to Stream Handler" ./logfile.log
###[2015-12-29 03:35:41,306]  INFO [L:com.tfsc.ilabs.chronos.queue.stream.impl.ChronosQueueStreamConsumer T:'pool-356-thread-7' I: IS: TR:STARTUP SQ:41047 ND:]  - Pushing chronos event to Stream Handler. ClientID:nemo-client-capitalone StreamID:nemo-client-capitaloneva1exitsurvey-event-handlerOEEvent PartitionID:2 CorrelationId:724a42a7-68ad-43fe-abe3-d485f67749ce eventRaisedTime 1,451,359,836,403
eventTypes=$1
threshold=$2
logstmt=$3
filepath=$4

eventType=(${eventTypes//,/ })
criticalTypes=

##status
_OK=0
_CRITICAL=2
status=$_OK
criticalCount=1;

for i in "${eventType[@]}"
do
        log=`grep "$logstmt.*$i.*" $filepath | tail -1`

        eventRaisedTime=`echo $log | grep -o "eventRaisedTime.*" | cut -d' ' -f2 | tr -d ','`

                logDate=`echo $log | cut -d']' -f1 | cut -d'[' -f2`
                eventProcessedTime=`date --date="$logDate" +%s%3N`

        diff=`expr $eventProcessedTime - $eventRaisedTime`

        if [ "$diff" -ge "$threshold" ]; then
                        status=$_CRITICAL
                        criticalTypes[$criticalCount]="$i is processed with a lag of $diff milliseconds"
                        criticalLogs[$criticalCount]=$log
                        criticalCount=$((criticalCount+1))
        fi
done


if [ "$status" == "$_CRITICAL" ]; then
        echo "CRITICAL: There is a lag in event processing"
        echo "__OUTPUT__"
        for i in "${criticalTypes[@]}"
        do
                echo $i
        done
        echo "__DATA__"
        for i in "${criticalLogs[@]}"
        do
                echo $i
        done
else
        echo "OK: Events are processed with expected delay of less than $threshold milliseconds"
fi

exit $status
