#!/bin/bash

cat *err*|awk '/Error_code/ {print $NF}'|sort|uniq -c

while read -a line;do echo ${line[0]} $(nslookup ${line[1]}|grep name|cut -d= -f2);done< <(netstat -napl|grep 3306|awk '{print $5}'|cut -d: -f1|sort|uniq -c|sort -k1 -nr);

# perror <error code>
