#!/bin/bash
#Given the below binary tree and sum = 22,
#
#      5
#     / \
#    4   8
#   /   / \
#  11  13  4
# /  \      \
#7    2      1
#
#return true, as there exist a root-to-leaf path 5->4->11->2 which sum is 22.
#

## First, how to represent that tree
#5
#5.4
#5.8
#5.4.11
#5.8.13
#5.8.4
#5.8.4.1
#5.4.11.2
#5.3.11.7
#
#

# Save above to t_tree.dat

while IFS='.' read -a path;do total=0;for i in ${!path[@]}; do total=$(echo $(($total + ${path[i]})) );if [ $total -eq 22 ];then echo $total:"${path[@]}";fi; done;done <t_tree.dat

